name: Arduino compile

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile Arduino
        uses: arduino/compile-sketches@v1.0.1
        with:
          libraries: |
            - Arduino_FastLED
          sketch-paths: |
            - ./LED/
